/* ============================================================
   WORLD COUNTRY QUIZ — country dataset
   tier: 1 = 初級プール向け（有名国）, 2 = 中級プール向け, 3 = 上級のみ
   a3  : ISO3166-1 alpha-3（地図データとの照合キー）
   a2  : ISO3166-1 alpha-2（国旗画像 flagcdn.com 用、小文字）
   geoNames: 地図データ側の名前ゆらぎ対策の予備マッチ候補（英語）
   ============================================================ */
(function(global){
  function c(a3, a2, ja, en, tier, aliases, geoNames){
    return { a3, a2, ja, en, tier, aliases: aliases || [], geoNames: geoNames || [en] };
  }

  const COUNTRIES = [
    // ---- ASIA ----
    c("JPN","jp","日本","Japan",1,["にほん","にっぽん"]),
    c("CHN","cn","中国","China",1,["中華人民共和国","ちゅうごく","ちゅうかじんみんきょうわこく"]),
    c("KOR","kr","韓国","South Korea",1,["大韓民国","かんこく","だいかんみんこく"]),
    c("PRK","kp","北朝鮮","North Korea",2,["朝鮮民主主義人民共和国","きたちょうせん","ちょうせんみんしゅしゅぎじんみんきょうわこく"]),
    c("IND","in","インド","India",1,[]),
    c("IDN","id","インドネシア","Indonesia",1,[]),
    c("THA","th","タイ","Thailand",1,[]),
    c("VNM","vn","ベトナム","Vietnam",1,[]),
    c("PHL","ph","フィリピン","Philippines",1,[]),
    c("MYS","my","マレーシア","Malaysia",2,[]),
    c("SGP","sg","シンガポール","Singapore",2,[]),
    c("MMR","mm","ミャンマー","Myanmar",2,["ビルマ"],["Myanmar","Burma"]),
    c("KHM","kh","カンボジア","Cambodia",2,[]),
    c("LAO","la","ラオス","Laos",2,[]),
    c("MNG","mn","モンゴル","Mongolia",2,[]),
    c("NPL","np","ネパール","Nepal",2,[]),
    c("BGD","bd","バングラデシュ","Bangladesh",2,[]),
    c("LKA","lk","スリランカ","Sri Lanka",2,[]),
    c("BTN","bt","ブータン","Bhutan",3,[]),
    c("MDV","mv","モルディブ","Maldives",2,[]),
    c("PAK","pk","パキスタン","Pakistan",2,[]),
    c("AFG","af","アフガニスタン","Afghanistan",3,[]),
    c("KAZ","kz","カザフスタン","Kazakhstan",2,[]),
    c("UZB","uz","ウズベキスタン","Uzbekistan",2,[]),
    c("TKM","tm","トルクメニスタン","Turkmenistan",3,[]),
    c("TJK","tj","タジキスタン","Tajikistan",3,[]),
    c("KGZ","kg","キルギス","Kyrgyzstan",3,[]),
    c("TWN","tw","台湾","Taiwan",2,["たいわん"]),
    c("SAU","sa","サウジアラビア","Saudi Arabia",1,[]),
    c("ARE","ae","アラブ首長国連邦","United Arab Emirates",2,["UAE","アラブ首長国連邦"]),
    c("ISR","il","イスラエル","Israel",2,[]),
    c("TUR","tr","トルコ","Turkey",1,["トゥルキエ"],["Turkey","Türkiye"]),
    c("IRN","ir","イラン","Iran",2,[]),
    c("IRQ","iq","イラク","Iraq",2,[]),
    c("SYR","sy","シリア","Syria",3,[]),
    c("JOR","jo","ヨルダン","Jordan",2,[]),
    c("LBN","lb","レバノン","Lebanon",2,[]),
    c("YEM","ye","イエメン","Yemen",3,[]),
    c("OMN","om","オマーン","Oman",2,[]),
    c("KWT","kw","クウェート","Kuwait",2,[]),
    c("QAT","qa","カタール","Qatar",2,[]),
    c("BHR","bh","バーレーン","Bahrain",2,[]),
    c("ARM","am","アルメニア","Armenia",2,[]),
    c("AZE","az","アゼルバイジャン","Azerbaijan",2,[]),
    c("GEO","ge","ジョージア","Georgia",2,["グルジア"]),
    c("CYP","cy","キプロス","Cyprus",2,[]),
    c("BRN","bn","ブルネイ","Brunei",3,[]),
    c("TLS","tl","東ティモール","Timor-Leste",3,["ティモール","ひがしてぃもーる"]),

    // ---- EUROPE ----
    c("GBR","gb","イギリス","United Kingdom",1,["英国","連合王国","えいこく","れんごうおうこく"]),
    c("FRA","fr","フランス","France",1,[]),
    c("DEU","de","ドイツ","Germany",1,[]),
    c("ITA","it","イタリア","Italy",1,[]),
    c("ESP","es","スペイン","Spain",1,[]),
    c("PRT","pt","ポルトガル","Portugal",1,[]),
    c("NLD","nl","オランダ","Netherlands",1,["ネーデルラント"]),
    c("BEL","be","ベルギー","Belgium",2,[]),
    c("CHE","ch","スイス","Switzerland",1,[]),
    c("AUT","at","オーストリア","Austria",2,[]),
    c("SWE","se","スウェーデン","Sweden",1,[]),
    c("NOR","no","ノルウェー","Norway",1,[]),
    c("DNK","dk","デンマーク","Denmark",1,[]),
    c("FIN","fi","フィンランド","Finland",1,[]),
    c("ISL","is","アイスランド","Iceland",2,[]),
    c("IRL","ie","アイルランド","Ireland",2,[]),
    c("GRC","gr","ギリシャ","Greece",1,["ギリシア"]),
    c("POL","pl","ポーランド","Poland",1,[]),
    c("CZE","cz","チェコ","Czechia",2,["チェコ共和国","ちぇこきょうわこく"],["Czechia","Czech Republic"]),
    c("SVK","sk","スロバキア","Slovakia",2,["スロヴァキア"]),
    c("HUN","hu","ハンガリー","Hungary",2,[]),
    c("ROU","ro","ルーマニア","Romania",2,[]),
    c("BGR","bg","ブルガリア","Bulgaria",2,[]),
    c("UKR","ua","ウクライナ","Ukraine",1,[]),
    c("BLR","by","ベラルーシ","Belarus",2,[]),
    c("MDA","md","モルドバ","Moldova",3,[]),
    c("RUS","ru","ロシア","Russia",1,["ロシア連邦","ろしあれんぽう"]),
    c("EST","ee","エストニア","Estonia",2,[]),
    c("LVA","lv","ラトビア","Latvia",2,[]),
    c("LTU","lt","リトアニア","Lithuania",2,[]),
    c("HRV","hr","クロアチア","Croatia",2,[]),
    c("SVN","si","スロベニア","Slovenia",2,[]),
    c("BIH","ba","ボスニア・ヘルツェゴビナ","Bosnia and Herzegovina",3,[]),
    c("SRB","rs","セルビア","Serbia",2,[]),
    c("MNE","me","モンテネグロ","Montenegro",3,[]),
    c("MKD","mk","北マケドニア","North Macedonia",3,["マケドニア","きたまけどにあ"]),
    c("ALB","al","アルバニア","Albania",3,[]),
    c("XKX","xk","コソボ","Kosovo",3,[]),
    c("MLT","mt","マルタ","Malta",2,[]),
    c("LUX","lu","ルクセンブルク","Luxembourg",2,[]),
    c("MCO","mc","モナコ","Monaco",3,[]),
    c("LIE","li","リヒテンシュタイン","Liechtenstein",3,[]),
    c("AND","ad","アンドラ","Andorra",3,[]),
    c("SMR","sm","サンマリノ","San Marino",3,[]),
    c("VAT","va","バチカン","Vatican City",3,["バチカン市国","ばちかんしこく"],["Vatican City","Vatican","Holy See"]),

    // ---- AFRICA ----
    c("EGY","eg","エジプト","Egypt",1,[]),
    c("LBY","ly","リビア","Libya",2,[]),
    c("TUN","tn","チュニジア","Tunisia",2,[]),
    c("DZA","dz","アルジェリア","Algeria",2,[]),
    c("MAR","ma","モロッコ","Morocco",2,[]),
    c("SDN","sd","スーダン","Sudan",3,[]),
    c("SSD","ss","南スーダン","South Sudan",3,["みなみすーだん"]),
    c("ETH","et","エチオピア","Ethiopia",2,[]),
    c("ERI","er","エリトリア","Eritrea",3,[]),
    c("DJI","dj","ジブチ","Djibouti",3,[]),
    c("SOM","so","ソマリア","Somalia",3,[]),
    c("KEN","ke","ケニア","Kenya",2,[]),
    c("UGA","ug","ウガンダ","Uganda",2,[]),
    c("TZA","tz","タンザニア","Tanzania",2,[]),
    c("RWA","rw","ルワンダ","Rwanda",3,[]),
    c("BDI","bi","ブルンジ","Burundi",3,[]),
    c("COD","cd","コンゴ民主共和国","Democratic Republic of the Congo",3,["コンゴ民主","こんごみんしゅきょうわこく","こんごみんしゅ"]),
    c("COG","cg","コンゴ共和国","Republic of the Congo",3,["コンゴ","こんごきょうわこく"]),
    c("CAF","cf","中央アフリカ共和国","Central African Republic",3,["中央アフリカ","ちゅうおうあふりかきょうわこく","ちゅうおうあふりか"]),
    c("CMR","cm","カメルーン","Cameroon",2,[]),
    c("TCD","td","チャド","Chad",3,[]),
    c("GAB","ga","ガボン","Gabon",3,[]),
    c("GNQ","gq","赤道ギニア","Equatorial Guinea",3,["せきどうぎにあ"]),
    c("NGA","ng","ナイジェリア","Nigeria",2,[]),
    c("NER","ne","ニジェール","Niger",3,[]),
    c("BEN","bj","ベナン","Benin",3,[]),
    c("TGO","tg","トーゴ","Togo",3,[]),
    c("GHA","gh","ガーナ","Ghana",2,[]),
    c("CIV","ci","コートジボワール","Ivory Coast",2,["コートジボワール共和国","こーとじぼわーるきょうわこく"],["Ivory Coast","Côte d'Ivoire","Cote d'Ivoire"]),
    c("LBR","lr","リベリア","Liberia",3,[]),
    c("SLE","sl","シエラレオネ","Sierra Leone",3,[]),
    c("GIN","gn","ギニア","Guinea",3,[]),
    c("GNB","gw","ギニアビサウ","Guinea-Bissau",3,[]),
    c("SEN","sn","セネガル","Senegal",2,[]),
    c("GMB","gm","ガンビア","Gambia",3,[]),
    c("MLI","ml","マリ","Mali",3,[]),
    c("BFA","bf","ブルキナファソ","Burkina Faso",3,[]),
    c("MRT","mr","モーリタニア","Mauritania",3,[]),
    c("CPV","cv","カーボベルデ","Cabo Verde",3,["カボベルデ"]),
    c("STP","st","サントメ・プリンシペ","Sao Tome and Principe",3,[]),
    c("ZAF","za","南アフリカ","South Africa",1,["みなみあふりか"]),
    c("NAM","na","ナミビア","Namibia",2,[]),
    c("BWA","bw","ボツワナ","Botswana",2,[]),
    c("ZWE","zw","ジンバブエ","Zimbabwe",2,[]),
    c("ZMB","zm","ザンビア","Zambia",2,[]),
    c("MWI","mw","マラウイ","Malawi",3,[]),
    c("MOZ","mz","モザンビーク","Mozambique",2,[]),
    c("AGO","ao","アンゴラ","Angola",2,[]),
    c("LSO","ls","レソト","Lesotho",3,[]),
    c("SWZ","sz","エスワティニ","Eswatini",3,["スワジランド"]),
    c("MDG","mg","マダガスカル","Madagascar",2,[]),
    c("MUS","mu","モーリシャス","Mauritius",2,[]),
    c("SYC","sc","セーシェル","Seychelles",3,[]),
    c("COM","km","コモロ","Comoros",3,[]),

    // ---- AMERICAS ----
    c("USA","us","アメリカ合衆国","United States of America",1,["アメリカ","米国","合衆国","べいこく","がっしゅうこく"]),
    c("CAN","ca","カナダ","Canada",1,[]),
    c("MEX","mx","メキシコ","Mexico",1,[]),
    c("GTM","gt","グアテマラ","Guatemala",3,[]),
    c("BLZ","bz","ベリーズ","Belize",3,[]),
    c("HND","hn","ホンジュラス","Honduras",3,[]),
    c("SLV","sv","エルサルバドル","El Salvador",3,[]),
    c("NIC","ni","ニカラグア","Nicaragua",3,[]),
    c("CRI","cr","コスタリカ","Costa Rica",2,[]),
    c("PAN","pa","パナマ","Panama",2,[]),
    c("CUB","cu","キューバ","Cuba",2,[]),
    c("JAM","jm","ジャマイカ","Jamaica",2,[]),
    c("HTI","ht","ハイチ","Haiti",3,[]),
    c("DOM","do","ドミニカ共和国","Dominican Republic",2,["どみにかきょうわこく"]),
    c("BHS","bs","バハマ","Bahamas",3,[]),
    c("TTO","tt","トリニダード・トバゴ","Trinidad and Tobago",3,[]),
    c("BRB","bb","バルバドス","Barbados",3,[]),
    c("LCA","lc","セントルシア","Saint Lucia",3,[]),
    c("GRD","gd","グレナダ","Grenada",3,[]),
    c("VCT","vc","セントビンセントおよびグレナディーン諸島","Saint Vincent and the Grenadines",3,["セントビンセント","せんとびんせんとおよびぐれなでぃーんしょとう"]),
    c("ATG","ag","アンティグア・バーブーダ","Antigua and Barbuda",3,[]),
    c("KNA","kn","セントクリストファー・ネイビス","Saint Kitts and Nevis",3,[]),
    c("DMA","dm","ドミニカ国","Dominica",3,[]),
    c("COL","co","コロンビア","Colombia",2,[]),
    c("VEN","ve","ベネズエラ","Venezuela",2,[]),
    c("ECU","ec","エクアドル","Ecuador",2,[]),
    c("PER","pe","ペルー","Peru",2,[]),
    c("BOL","bo","ボリビア","Bolivia",2,[]),
    c("BRA","br","ブラジル","Brazil",1,[]),
    c("PRY","py","パラグアイ","Paraguay",2,[]),
    c("URY","uy","ウルグアイ","Uruguay",2,[]),
    c("ARG","ar","アルゼンチン","Argentina",1,[]),
    c("CHL","cl","チリ","Chile",1,[]),
    c("GUY","gy","ガイアナ","Guyana",3,[]),
    c("SUR","sr","スリナム","Suriname",3,[]),

    // ---- OCEANIA ----
    c("AUS","au","オーストラリア","Australia",1,[]),
    c("NZL","nz","ニュージーランド","New Zealand",1,[]),
    c("PNG","pg","パプアニューギニア","Papua New Guinea",2,[]),
    c("FJI","fj","フィジー","Fiji",2,[]),
    c("SLB","sb","ソロモン諸島","Solomon Islands",3,["そろもんしょとう"]),
    c("VUT","vu","バヌアツ","Vanuatu",3,[]),
    c("WSM","ws","サモア","Samoa",3,[]),
    c("TON","to","トンガ","Tonga",3,[]),
    c("KIR","ki","キリバス","Kiribati",3,[]),
    c("TUV","tv","ツバル","Tuvalu",3,[]),
    c("NRU","nr","ナウル","Nauru",3,[]),
    c("PLW","pw","パラオ","Palau",3,[]),
    c("MHL","mh","マーシャル諸島","Marshall Islands",3,["まーしゃるしょとう"]),
    c("FSM","fm","ミクロネシア連邦","Micronesia",3,["ミクロネシア","みくろねしられんぽう"]),

    // ---- OTHER ----
    c("PSE","ps","パレスチナ","Palestine",3,[])
  ];

  /* ---- 大陸区分（地図の拡大表示に使用） ---- */
  const CONTINENT_A3 = {
    asia: "JPN,CHN,KOR,PRK,IND,IDN,THA,VNM,PHL,MYS,SGP,MMR,KHM,LAO,MNG,NPL,BGD,LKA,BTN,MDV,PAK,AFG,KAZ,UZB,TKM,TJK,KGZ,TWN,SAU,ARE,ISR,TUR,IRN,IRQ,SYR,JOR,LBN,YEM,OMN,KWT,QAT,BHR,ARM,AZE,GEO,CYP,BRN,TLS,PSE".split(","),
    europe: "GBR,FRA,DEU,ITA,ESP,PRT,NLD,BEL,CHE,AUT,SWE,NOR,DNK,FIN,ISL,IRL,GRC,POL,CZE,SVK,HUN,ROU,BGR,UKR,BLR,MDA,RUS,EST,LVA,LTU,HRV,SVN,BIH,SRB,MNE,MKD,ALB,XKX,MLT,LUX,MCO,LIE,AND,SMR,VAT".split(","),
    africa: "EGY,LBY,TUN,DZA,MAR,SDN,SSD,ETH,ERI,DJI,SOM,KEN,UGA,TZA,RWA,BDI,COD,COG,CAF,CMR,TCD,GAB,GNQ,NGA,NER,BEN,TGO,GHA,CIV,LBR,SLE,GIN,GNB,SEN,GMB,MLI,BFA,MRT,CPV,STP,ZAF,NAM,BWA,ZWE,ZMB,MWI,MOZ,AGO,LSO,SWZ,MDG,MUS,SYC,COM".split(","),
    north_america: "USA,CAN,MEX,GTM,BLZ,HND,SLV,NIC,CRI,PAN,CUB,JAM,HTI,DOM,BHS,TTO,BRB,LCA,GRD,VCT,ATG,KNA,DMA".split(","),
    south_america: "COL,VEN,ECU,PER,BOL,BRA,PRY,URY,ARG,CHL,GUY,SUR".split(","),
    oceania: "AUS,NZL,PNG,FJI,SLB,VUT,WSM,TON,KIR,TUV,NRU,PLW,MHL,FSM".split(",")
  };
  const A3_TO_CONTINENT = {};
  Object.keys(CONTINENT_A3).forEach(cont=>{
    CONTINENT_A3[cont].forEach(a3=>{ A3_TO_CONTINENT[a3] = cont; });
  });
  COUNTRIES.forEach(c=>{ c.continent = A3_TO_CONTINENT[c.a3] || "asia"; });

  /* ---- 大陸ごとの地図表示範囲（緯度経度 or 中心+ズーム） ---- */
  const CONTINENT_VIEW = {
    asia:           { bounds: [[-11, 25], [55, 150]] },
    europe:         { bounds: [[34, -25], [71, 45]] },
    africa:         { bounds: [[-35, -18], [38, 52]] },
    north_america:  { bounds: [[5, -170], [75, -50]] },
    south_america:  { bounds: [[-56, -82], [13, -34]] },
    oceania:        { center: [-22, 155], zoom: 3 }
  };

  /* ---- 首都データ（複数首都がある国は配列で複数候補を用意。ひらがな読みも別解として含む） ---- */
  const CAPITALS_BY_A3 = {
    JPN:["東京","とうきょう"], CHN:["北京","ペキン","ぺきん"], KOR:["ソウル"], PRK:["ピョンヤン","平壌","へいじょう"],
    IND:["ニューデリー"], IDN:["ジャカルタ","ヌサンタラ"], THA:["バンコク"], VNM:["ハノイ"], PHL:["マニラ"],
    MYS:["クアラルンプール"], SGP:["シンガポール"], MMR:["ネピドー"], KHM:["プノンペン"], LAO:["ビエンチャン"],
    MNG:["ウランバートル"], NPL:["カトマンズ"], BGD:["ダッカ"], LKA:["スリジャヤワルダナプラコッテ","コロンボ"],
    BTN:["ティンプー"], MDV:["マレ"], PAK:["イスラマバード"], AFG:["カブール"], KAZ:["アスタナ"], UZB:["タシケント"],
    TKM:["アシガバット"], TJK:["ドゥシャンベ"], KGZ:["ビシュケク"], TWN:["台北","たいぺい"], SAU:["リヤド"],
    ARE:["アブダビ"], ISR:["エルサレム","テルアビブ"], TUR:["アンカラ"], IRN:["テヘラン"], IRQ:["バグダッド"],
    SYR:["ダマスカス"], JOR:["アンマン"], LBN:["ベイルート"], YEM:["サナア","アデン"], OMN:["マスカット"],
    KWT:["クウェートシティ"], QAT:["ドーハ"], BHR:["マナーマ"], ARM:["エレバン"], AZE:["バクー"], GEO:["トビリシ"],
    CYP:["ニコシア"], BRN:["バンダルスリブガワン"], TLS:["ディリ"], PSE:["エルサレム","ラマッラ"],

    GBR:["ロンドン"], FRA:["パリ"], DEU:["ベルリン"], ITA:["ローマ"], ESP:["マドリード"], PRT:["リスボン"],
    NLD:["アムステルダム","デンハーグ"], BEL:["ブリュッセル"], CHE:["ベルン"], AUT:["ウィーン"], SWE:["ストックホルム"],
    NOR:["オスロ"], DNK:["コペンハーゲン"], FIN:["ヘルシンキ"], ISL:["レイキャビク"], IRL:["ダブリン"], GRC:["アテネ"],
    POL:["ワルシャワ"], CZE:["プラハ"], SVK:["ブラチスラバ"], HUN:["ブダペスト"], ROU:["ブカレスト"], BGR:["ソフィア"],
    UKR:["キーウ","キエフ"], BLR:["ミンスク"], MDA:["キシナウ"], RUS:["モスクワ"], EST:["タリン"], LVA:["リガ"],
    LTU:["ビリニュス"], HRV:["ザグレブ"], SVN:["リュブリャナ"], BIH:["サラエボ"], SRB:["ベオグラード"],
    MNE:["ポドゴリツァ"], MKD:["スコピエ"], ALB:["ティラナ"], XKX:["プリシュティナ"], MLT:["バレッタ"],
    LUX:["ルクセンブルク"], MCO:["モナコ"], LIE:["ファドゥーツ"], AND:["アンドラ・ラ・ベリャ"], SMR:["サンマリノ"],
    VAT:["バチカン市国","バチカン","ばちかんしこく"],

    EGY:["カイロ"], LBY:["トリポリ"], TUN:["チュニス"], DZA:["アルジェ"], MAR:["ラバト"], SDN:["ハルツーム"],
    SSD:["ジュバ"], ETH:["アディスアベバ"], ERI:["アスマラ"], DJI:["ジブチ"], SOM:["モガディシュ"], KEN:["ナイロビ"],
    UGA:["カンパラ"], TZA:["ドドマ","ダルエスサラーム"], RWA:["キガリ"], BDI:["ギテガ","ブジュンブラ"],
    COD:["キンシャサ"], COG:["ブラザビル"], CAF:["バンギ"], CMR:["ヤウンデ"], TCD:["ンジャメナ"], GAB:["リーブルビル"],
    GNQ:["マラボ"], NGA:["アブジャ"], NER:["ニアメ"], BEN:["ポルトノボ","コトヌー"], TGO:["ロメ"], GHA:["アクラ"],
    CIV:["ヤムスクロ","アビジャン"], LBR:["モンロビア"], SLE:["フリータウン"], GIN:["コナクリ"], GNB:["ビサウ"],
    SEN:["ダカール"], GMB:["バンジュール"], MLI:["バマコ"], BFA:["ワガドゥグー"], MRT:["ヌアクショット"],
    CPV:["プライア"], STP:["サントメ"], ZAF:["プレトリア","ケープタウン","ブルームフォンテーン"], NAM:["ウィントフック"],
    BWA:["ハボローネ"], ZWE:["ハラレ"], ZMB:["ルサカ"], MWI:["リロングウェ"], MOZ:["マプト"], AGO:["ルアンダ"],
    LSO:["マセル"], SWZ:["ムババーネ","ロバンバ"], MDG:["アンタナナリボ"], MUS:["ポートルイス"], SYC:["ビクトリア"],
    COM:["モロニ"],

    USA:["ワシントンD.C.","ワシントン"], CAN:["オタワ"], MEX:["メキシコシティ"], GTM:["グアテマラシティ"],
    BLZ:["ベルモパン"], HND:["テグシガルパ"], SLV:["サンサルバドル"], NIC:["マナグア"], CRI:["サンホセ"],
    PAN:["パナマシティ"], CUB:["ハバナ"], JAM:["キングストン"], HTI:["ポルトープランス"], DOM:["サントドミンゴ"],
    BHS:["ナッソー"], TTO:["ポートオブスペイン"], BRB:["ブリッジタウン"], LCA:["カストリーズ"], GRD:["セントジョージズ"],
    VCT:["キングスタウン"], ATG:["セントジョンズ"], KNA:["バセテール"], DMA:["ロゾー"], COL:["ボゴタ"],
    VEN:["カラカス"], ECU:["キト"], PER:["リマ"], BOL:["スクレ","ラパス"], BRA:["ブラジリア"], PRY:["アスンシオン"],
    URY:["モンテビデオ"], ARG:["ブエノスアイレス"], CHL:["サンティアゴ"], GUY:["ジョージタウン"], SUR:["パラマリボ"],

    AUS:["キャンベラ"], NZL:["ウェリントン"], PNG:["ポートモレスビー"], FJI:["スバ"], SLB:["ホニアラ"],
    VUT:["ポートビラ"], WSM:["アピア"], TON:["ヌクアロファ"], KIR:["タラワ","南タラワ","みなみたらわ"],
    TUV:["フナフティ"], NRU:["ヤレン"], PLW:["マルキョク"], MHL:["マジュロ"], FSM:["パリキール"]
  };
  COUNTRIES.forEach(c=>{ c.capitals = CAPITALS_BY_A3[c.a3] || []; });

  global.WORLD_QUIZ_COUNTRIES = COUNTRIES;
  global.WORLD_QUIZ_CONTINENT_VIEW = CONTINENT_VIEW;
})(window);
